name: QWEQWE
on:
  workflow_dispatch:
env:
  test_url: ${{ secrets.TEST_URL }}
jobs:
  screenshot:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - id: foo
      run: echo random-number ${{ steps.foo.outputs.random-number }}
